name: BB842
channels:
  - conda-forge
dependencies:
  - dask[complete]
  - holoviews
  - hvplot
  - jupyterlab
  - notebook
  - panel
  - scikit-learn
  - diskcache
  - requests
  - pyarrow
  - openpyxl
  - datashader
  - scikit-learn
  - pylint
  - mypy
  - pytest
  - isort
  - black
  - autoflake
  - cartopy
  - geoviews
  - voila
  - jupyter-panel-proxy
  - pip
  - pandas
  - matplotlib
  - numpy
  - scipy
  - pathlib
  - pip:
    - git+https://github.com/holoviz/panel.git#egg=panel